name: Deploy Docker Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY_NAME }}
  LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME }}

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run tests
        run: |
          python -m unittest discover -s tests -v

  codeql:
    name: CodeQL Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Analyze
        uses: github/codeql-action/analyze@v3

  build_scan:
    name: Build & Trivy Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t lambda-local:${{ github.sha }} .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: lambda-local:${{ github.sha }}
          format: table
          severity: HIGH,CRITICAL
          exit-code: 0

  ai-security-review:
    name: AI Security Review
    runs-on: ubuntu-latest
    needs:
      - test
      - codeql
      - build_scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install google-genai
          
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run AI Security Review
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          if [ -z "$GEMINI_API_KEY" ]; then
            echo "GEMINI_API_KEY not configured. Skipping AI security review."
            exit 0
          fi

          python scripts/ai_action.py 

      - name: Publish AI Report
        run: |
          echo "# 🤖 AI Security Review" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat ai_summary.txt >> $GITHUB_STEP_SUMMARY

      - name: Upload AI Report
        uses: actions/upload-artifact@v4
        with:
         name: ai-security-report
         path: ai_summary.txt

      - name: Check AI Score
        run: | 
           SCORE=$(grep "Security Score" ai_summary.txt | grep -o '[0-9]\+')
#           if [ "$SCORE" -lt 7 ]; then
#           echo "AI score too low"
#           exit 1
#           fi

  deploy:
    name: Deploy Lambda
    needs:
      - test
      - codeql
      - build_scan
      - ai-security-review

    environment:
      name: production

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Variables
        run: |
          echo "AWS_REGION=${{ vars.AWS_REGION }}"
          echo "ECR_REPOSITORY=${{ vars.ECR_REPOSITORY_NAME }}"
          echo "LAMBDA_FUNCTION_NAME=${{ vars.LAMBDA_FUNCTION_NAME }}"

          test -n "${{ vars.AWS_REGION }}"
          test -n "${{ vars.ECR_REPOSITORY_NAME }}"
          test -n "${{ vars.LAMBDA_FUNCTION_NAME }}"
          test -n "${{ vars.AWS_ROLE_TO_ASSUME }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $REGISTRY/$ECR_REPOSITORY:latest \
            .

      - name: Push Docker Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$ECR_REPOSITORY:latest

      - name: Update Lambda Function
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --image-uri $REGISTRY/$ECR_REPOSITORY:latest

      - name: Wait For Lambda Update
        run: |
          aws lambda wait function-updated \
            --function-name $LAMBDA_FUNCTION_NAME

      - name: Verify Deployment
        run: |
          aws lambda get-function \
            --function-name $LAMBDA_FUNCTION_NAME